services:
  - type: web
    name: bluestock-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn ipo_backend.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: ipo_backend.settings
      - key: PYTHON_VERSION
        value: 3.11.8
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: your-app-name.onrender.com
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
