# Generated by Django 5.0.6 on 2025-05-23 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='drhp_pdf',
            field=models.FileField(upload_to='pdfs/drhp/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='rhp_pdf',
            field=models.FileField(upload_to='pdfs/rhp/'),
        ),
    ]
